### ISSUE TITLE
Rename SWEP1R to SWE1R

### ISSUE THREAD

**Issue by JayFoxRox** [OpenSWE1R/swe1r-tools#5]
Gets more google hits.

**Comment by Verilion** [comment]
Hi!

I've been tinkering with this for a bit now. I wanted to extract the contents of podracing (I am on windows) and I tried to reverse engineer your script a bit. For instance, I renamed this:

 with open("c:/tmp/model-%d-b.bin" % i, 'wb') as t:

After running the script I got a long list of .bin files (as expected from the extension added in the script), but I am not sure exactly what to do with these? I was expecting .obj files or similar.

What can I do from here? Thanks!

**Comment by JayFoxRox** [comment]
Please create a new issue for this instead of posting it here. Also see #1

**Comment by Verilion** [comment]
Sorry, I am not familiar with GitHub, to be honest. Thanks for the quick response!
